### PR TITLE
Binary body recording

### PR DESCRIPTION
**Pull request by I159**
During recording a S3 object retrieving request the library raises TypeError while the response is totally valid and changing actual response, thus request couldn't be finished.

### CODE REVIEW

**Comment by kiwiz** [comment]
@garnaat We started hitting this issue too. Could this PR be merged?

**Comment by garnaat** [comment]
There are some merge conflicts at the moment.  If the author wants to resolve those, that would be great.  Otherwise I can do it and get it merged.

**Comment by davidyum** [comment]
+1 just ran into this error too. Would be great if you could merge

**Comment by TheBishopOfSoho** [comment]
> +1 just ran into this error too. Would be great if you could merge

Another +1 to the mix, ran into this while recording a session that pulls a file from S3.

**Comment by adhorn** [comment]
+1  running into this issue to with AppConfig.

**Comment by garnaat** [comment]
This should be fixed with a different approach in #79

**Pull request closed without merging**
