### PR TITLE
Adds @placebo_session decorator

### PR DESCRIPTION
**Pull request by Miserlou**
This adds the @placebo_session decorator mentioned in #40. Docs and test included.

This work is largely just done by @mathom - I'm just moving it upstream.

### CODE REVIEW

**Comment by garnaat** [comment]
Thanks!

**Comment by vascop** [comment]
Will this be pushed to pypi soon?

**Comment by garnaat** [comment]
Just pushed a ``0.8.0``

**Comment by vascop** [comment]
Thanks. I tried it and PLACEBO_DIR is going into __file__ which is wherever placebo is installed, in my case, my virtual environment. I also think that it should be configurable in some way. But definitely shouldn't be going into the virtual environment as a default.

**Comment by garnaat** [comment]
It seems like ``PLACEBO_DIR`` should be an environment variable?

**Pull request merged**
