### PR TITLE
Fix for issues with saving responses with datetime objects (#5)

### PR DESCRIPTION
**Pull request by gffhcks**

### CODE REVIEW

**Comment by garnaat** [comment]
Looks good. It would be nice to have a unit test for the round-trip conversion.

**Comment by gffhcks** [comment]
@garnaat If I have the time today I'll add a test. Are you okay with introducing mock as a test dependency for 2.x? Or would you prefer that the test actually write to file and then reload it?

**Comment by garnaat** [comment]
I don't have an issue with a test dependency on mock.

**Comment by gffhcks** [comment]
@garnaat Just added tests for conversion to and from JSON with `datetime` objects. I couldn't find a good way to get the saved JSON document from a mocked open method, so instead I modified `save()` and `load()` to support file-like objects as well as filesystem paths. I then used `StringIO` to simulate files and compare the results. Hopefully that works for you, let me know if you have a better approach.

**Comment by garnaat** [comment]
Thanks!  I'll do a new release now.

**Pull request merged**
